wesabe.require('xml.Text')
wesabe.require('xml.Attribute')
wesabe.require('xml.OpenTag')
wesabe.require('xml.CloseTag')
wesabe.require('xml.Element')
wesabe.require('xml.Parser')
wesabe.require('xml.Document')
wesabe.require('xml.NodeList')
