#!/usr/bin/env ruby

begin
  require 'bundler'
rescue LoadError
  begin
    require 'rubygems'
    require 'bundler'
  rescue LoadError => e
    $stderr.puts "ERROR: Unable to generate because an error occurred while loading: #{e}"
  end
end

Bundler.setup
require 'templater'

generators = File.expand_path('../generators', __FILE__)
$:.unshift generators unless $:.include? generators

require 'player'
require 'credential'

module SSU::Generators
  extend Templater::Manifold

  add :player, PlayerGenerator
  add :credential, CredentialGenerator

  desc "Generators for Players and Credentials, yo."

  run_cli Dir.pwd, $0, '0.1', ARGV
end
